te: 3784 - rule for checking if value of z-index property is a constant
spryker-sdk/frontend-sniffer pull request #11
Opened 2019-07-01 12:18 UTC by KostKravchenko

https://spryker.atlassian.net/browse/TE-3784

2019-07-01 12:40 UTC, supproduction requested changes

2019-07-01 12:40 UTC, supproduction commented on rules/mandatory-z-index-variable.js
> +            if (sass.exists) {
Please add 1 red line after `const`

2019-07-01 12:51 UTC, supproduction approved these changes

2019-07-10 14:19 UTC, FRITS-Kh requested changes

2019-07-10 14:19 UTC, FRITS-Kh commented on rules/mandatory-z-index-variable.js
> +            if (sass.exists) {
Please use early return.

2019-07-12 12:55 UTC, FRITS-Kh requested changes

2019-07-12 12:55 UTC, FRITS-Kh commented on rules/mandatory-z-index-variable.js
> +            if (zIndexRules) {
Please also refactor to return.

2019-07-12 13:21 UTC, merged