TE-3842: Added sniffed-disable global command
spryker-sdk/frontend-sniffer pull request #15
Opened 2019-07-16 16:14 UTC by supproduction

https://spryker.atlassian.net/browse/TE-3842

2019-07-17 09:24 UTC, KostKravchenko requested changes

2019-07-17 09:24 UTC, KostKravchenko commented on rules/correct-typescript-component-structure.js
> +            const { name: typescriptFileName, disabledSnifferRules, api: { external: { classes } } } = files.typescript;
please return step-by-step defragmentation

2019-07-17 09:24 UTC, KostKravchenko commented on rules/correct-twig-component-structure.js
> +            } = files.twig;
Please return step-by-step defragmentation

2019-07-17 09:24 UTC, KostKravchenko commented on rules/correct-typescript-component-structure.js
> +            const { name: typescriptFileName, disabledSnifferRules, api: { external: { classes } } } = files.typescript;
Please return step-by-step defragmentation

2019-07-19 09:15 UTC, tolerants requested changes

2019-07-19 09:15 UTC, tolerants commented on src/sniffer/test-outcome.ts
> +    errorMessage(message: string, type: string, name: string, path: string): string {
Suggest to rename into `formatMessage`.

2019-07-19 09:15 UTC, tolerants commented on rules/correct-scss-component-structure.js
> +            if (isSnifferDisabled(disabledSnifferRules, this.getName())) {
Suggest to implement a decorator for this check.

2019-07-19 09:15 UTC, tolerants commented on rules/correct-twig-component-structure.js
> +            const configDefinition = definitions.filter(definition => definition.name === 'config')[0];
Suggest to add a check if there is only one `config` object. And also the same about `data` object.

2019-07-22 15:18 UTC, tolerants approved these changes

2019-07-22 15:22 UTC, KostKravchenko approved these changes

2019-07-22 15:32 UTC, merged