TE-3768: Extension collector parsing to the project level
spryker-sdk/frontend-sniffer pull request #7
Opened 2019-06-26 14:53 UTC by supproduction

https://spryker.atlassian.net/browse/TE-3768
https://spryker.atlassian.net/browse/TE-3715 - CR

2019-07-01 12:12 UTC, KostKravchenko requested changes

2019-07-01 12:12 UTC, KostKravchenko commented on src/collector/components/index.ts
> +const limitedScanForFilesCollection = (scanForComponents) => iif(
if you use only one parameter it will be better:
const limitedScanForFilesCollection = scanForComponents => iif(

2019-07-01 12:12 UTC, KostKravchenko commented on src/collector/index.ts
> -        components: observableOutput[2]
Maybe it will be better to create constants for indexes in order to avoid magic numbers

2019-07-01 12:12 UTC, KostKravchenko commented on src/collector/styles/index.ts
> +const limitedScanForFilesCollection = (scanForFiles) => iif(
if you use only one parameter, you can write without brackets
const limitedScanForFilesCollection = scanForFiles => iif(

2019-07-01 12:21 UTC, supproduction commented on src/collector/index.ts
> -        components: observableOutput[2]
I do not use magic numbers in this case http://prntscr.com/o90sr8

2019-07-01 13:21 UTC, KostKravchenko approved these changes

2019-07-01 20:19 UTC, tolerants requested changes

2019-07-01 20:19 UTC, tolerants commented on config/collector.js
> +    scan: createScanConfig(['./'], '**/vendor/**/')
Please specify `spryker-shop`, we don't need to scan whole vendor.

2019-07-01 20:19 UTC, tolerants commented on src/collector/components/index.ts
> +import {iif, Observable, from} from 'rxjs';
These spaces wars... can you please add some spaces? :)

2019-07-01 20:19 UTC, tolerants commented on src/collector/components/index.ts
> +const logCollection = (level: string) => createLogger<IStyleFile[]>(`${level} Components:`, 'length');
Why `IStyleFile`?

2019-07-01 20:19 UTC, tolerants commented on src/collector/components/index.ts
> +        scanLevel: 'vendor'
I'd rename it to `core`. Please rename everywhere.

2019-07-01 20:19 UTC, tolerants commented on src/environment.ts
> +        const allowedLevelsPaths = ['project', 'vendor'];
There are a lot of usages of magic string `project` and `vendor`. Please move into configuration as constants.

2019-07-03 09:22 UTC, tolerants requested changes

2019-07-03 09:22 UTC, tolerants commented on config/collector.js
> +    scan: createScanConfig(['./'], '**/vendor/spryker/spryker-shop/Bundles/**/')
Please note we have split project with different structure.

2019-07-03 10:41 UTC, tolerants approved these changes

2019-07-03 10:44 UTC, merged