Feature/te 3773 check scss mixin content
spryker-sdk/frontend-sniffer pull request #9
Opened 2019-06-27 13:59 UTC by KostKravchenko

Ticket: https://spryker.atlassian.net/browse/TE-3773

2019-06-27 15:01 UTC, supproduction approved these changes

2019-07-01 12:36 UTC, supproduction requested changes

2019-07-01 12:36 UTC, supproduction commented on rules/mandatory-mixin-content.js
> +            if (sass.exists) {
Please remove unnecessary 1 red line

2019-07-03 06:59 UTC, tolerants requested changes

2019-07-03 06:59 UTC, tolerants commented on rules/mandatory-mixin-content.js
> +                    const { hasContent: isContent } = mixin;
Please don't change the variable name to `isContent`.

2019-07-03 07:00 UTC, tolerants requested changes

2019-07-03 07:00 UTC, tolerants commented on rules/mandatory-mixin-content.js
> +                    const convertedMixinText = stringify(mixin.tree);
Suggest to move constants definition before if.

2019-07-04 13:14 UTC, closed without merging